- name: check if cloud-hypervisor exists
  stat:
    path: $HOME/cloud-hypervisor
  register: cloud_hypervisor

- name: download cloud-hypervisor
  get_url:
    url: "https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v{{ chversion }}/cloud-hypervisor-static"
    dest: $HOME/cloud-hypervisor
    mode: '0755'
  when: not cloud_hypervisor.stat.exists

- name: ensure cloud-hypervisor is executable
  file:
    path: $HOME/cloud-hypervisor
    mode: '0755'
  when: cloud_hypervisor.stat.exists